# Generated by Django 4.0.5 on 2023-01-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetailShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(blank=True, max_length=70, null=True)),
                ('r_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WholeSaleShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(blank=True, max_length=70, null=True)),
                ('w_qty', models.IntegerField()),
            ],
        ),
    ]
